### ISSUE TITLE
A credential can be revoked multiple times.

### ISSUE THREAD

**Issue by azuzi** [uport-project/ethr-status-registry#74] opened 2020-08-17 08:39 UTC
I'm trying to revoke a credential multiple times ,but its possible because every time a new token is been created, so the hash is new and its possible to revoke a credential multiple times.

**Comment by mirceanis** [comment] 2020-08-17 10:04
If you create a new token, that is considered a new credential.
I don't understand if you are posting a bug. Can you please describe your problem in more detail?

**Comment by azuzi** [comment] 2020-08-17 11:05
The verifier , someone other than issuer, how he can verify the revocation status of a credential, then he needs the token. So token need to be generated again? or am I misunderstand the concept here.

**Comment by mirceanis** [comment] 2020-08-17 12:16
This revocation mechanism was designed with the JWT representation of credentials in mind.
When a new JWT is created it is considered to be a new credential.
The JWT is the credential, because only as a whole can it be verified.

If you generate the credential again, then a new JWT is created.
This new credential will be identical only If all the fields of the payload are identical (including `iat`, `nbf`, `exp`... everything) as well as the order in which they appear and the serialization of the payload and header JSONs, and it is signed by the same key.

The verifier does not need to regenerate the token. That would be impossible.
They need to decode it to figure out if it is revocable, which method of revocation is used and and where the revocation registry is located.
Once this decoding is done, the original token is the one that gets checked against the credential.

Again, please add some detail to your problem.
I can't figure out where the misunderstanding is happening based only on the questions you posed.
Please share some code, or a method, or a problem or an error message.

**Comment by azuzi** [comment] 2020-08-17 13:00
@mirceanis Thanks for the inside on VC revocation. It was my misundersatnding , because I understand it like the revocation and status verification works using the "credentialStatus" field from VC. But actually it's to be done using the extracted token of "credentialStatus" field from JWT VC's. Thanks for the reply.

**Comment by mirceanis** [comment] 2020-08-17 13:26
In theory, it could be used for other VC encodings, not just JWT but the prerequisite is that they can be expressed in a canonical form that hashes to the same hash, or rather that there is a truly unique identifier of the credential that can be used as the input for the hash.

The "credentialStatus" field of the VC (be it JWT or not) is supposed to point to the method and coordinates of the revocation mechanism, not dictate the status directly.
The credential embeds a "pointer" to the registry that can later be used to revoke it.

In the case of JWT, the truly unique identifier of a credential is the JWT itself so this library uses that as the input for the hash when checking for revocation.

I'm closing this. Please reopen if there is still some misunderstanding.

**Closed by mirceanis** 2020-08-17 13:26 UTC

**Comment by azuzi** [comment] 2020-08-18 09:15
Thanks for the clear answer.
